package com.rewordly.app.core.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject

/**
 * AES/GCM with a key generated inside the Android Keystore and never exported from it.
 *
 * The stored form is `base64(iv):base64(ciphertext)`. A fresh IV is generated by the platform for every
 * encryption, which is what GCM requires. No user-authentication requirement is set on the key, so reading the
 * settings never triggers a biometric prompt; the protection is that the raw key material is not on disk.
 */
class KeystoreSecretCipher @Inject constructor() : SecretCipher {
    override fun encrypt(plain: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val encrypted = cipher.doFinal(plain.toByteArray(Charsets.UTF_8))
        return Base64.encodeToString(cipher.iv, FLAGS) + SEPARATOR + Base64.encodeToString(encrypted, FLAGS)
    }

    override fun decrypt(encoded: String): String? {
        val separator = encoded.indexOf(SEPARATOR)
        if (separator <= 0 || separator == encoded.lastIndex) return null
        return try {
            val iv = Base64.decode(encoded.substring(0, separator), FLAGS)
            val body = Base64.decode(encoded.substring(separator + 1), FLAGS)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_BITS, iv))
            String(cipher.doFinal(body), Charsets.UTF_8)
        } catch (e: Exception) {
            // A restored backup or a wiped Keystore leaves undecryptable bytes behind. Treat them as "no key".
            null
        }
    }

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        val existing = keyStore.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry
        if (existing != null) return existing.secretKey

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val ALIAS = "rewordly_ai_key"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val TAG_BITS = 128
        const val SEPARATOR = ':'
        const val FLAGS = Base64.NO_WRAP
    }
}
